
### IRIS DATA

```{r data,echo=FALSE,cache=TRUE,message=FALSE,warning=FALSE,results='asis'}

#example using Iris data
library(PPforest)
library(PPtree)
library(reshape)
library(plyr)
library(ggplot2)
library(randomForest)


data.iris <- iris[,5:1]
training<- train_fn(iris[,5],.9)
test<-as.vector(1:length(iris[,5]))[!(1:length(iris[,5])%in%(training))]

result.boot.st <- mlply(data.frame(nt=c(5,10,50,100,500)), function(nt) {
  bootstrap_pp(data=data.iris,scale=TRUE,size.p=.9,training=training,test,strata=TRUE,ntree=nt,index="LDA") 
   }  
)  


#Tree.result <- PPtree_split("LDA",data.iris[training,1], data.iris[training,2:5],size.p=0.9)
#pp.cl <- PP.classify(data.iris[training,2:5],data.iris[training,1],Tree.result,1)


result.bagg.st <- llply(result.boot.st[1:5],function(x) bagging_pp(data=data.iris,boot=x,size.p=.9,training=training,test=test))

error.st <- sapply(result.bagg.st,function(x) x[[1]][1] )




   output<-bootstrap_pp(data.iris,scale=TRUE,size.p=.9,training,strata=TRUE,ntree=500,index="LDA") 
    b.pp <- bagging_pp(data.iris,scale=TRUE, strata=TRUE,output,training,test)


#proximity matrix
A<-matrix(0,ncol=150,nrow=150)
A[lower.tri(A,diag=T)]<-b.pp[[9]][,3]
A[upper.tri(A,diag=T)]
dA<-as.dist(1-A)
clA<-hclust(dA)
cl.h<-cutree(clA, k = 3)
qplot(y=Sepal.Width, x=Sepal.Length, data=iris,color=as.factor(cl.h))


km.A<-kmeans(A,centers=3)
qplot(y=Species, x=km.A$cluster,data=iris, group=km.A$cluster,geom="jitter" )
table(iris$Species, km.A$cluster)
qplot(y=Sepal.Width, x=Sepal.Length, data=iris,color=as.factor(km.A$cluster))
qplot(y=Petal.Length, x=Petal.Width, data=iris,color=as.factor(km.A$cluster))
qplot(y=Sepal.Length, x=Petal.Width, data=iris,color=as.factor(km.A$cluster))






#sacalo <- function(xx) {
 # ldply(xx[[1]], function(x) x[[2]]$Alpha.Keep)
#}
#sacalo(result.boot.st[[1]])
#jj1<-ldply(result.boot.st, sacalo)
#jj2<-ldply(result.boot.st[1:5], sacalo)

###




```

```{r table.res,echo=FALSE,dependson='data',results='asis'}
library(xtable)
aux <- c(5,10,50,100,500)

aaa<-xtable(cbind(aux,error,error.st),digits=5,caption="OOB error for PP.bagging with bootstrap samples without strata and with strata")
###
print(aaa,caption.placement="top",include.rownames=TRUE,include.colnames=TRUE)

```

Using PPtree with LDA the error is 0

```{r pp.iris,dependson='data',echo=TRUE,message=FALSE,warning=FALSE}
library(PPtree)
Tree.result <- PP.Tree("LDA",iris[training,5],iris[training,1:4])
test <- iris[-training,]
res<-PP.classify(test[,1:4],test[,5],Tree.result,1)
print(res[[1]]/length(res[[2]]))
```

Ussing the same data we run a random forest and the oob error is around 5%.

```{r rf.iris,depenson="data'",echo=FALSE,message=FALSE,warning=FALSE}
library(randomForest)
rf.iris<-randomForest(Species ~ ., data=iris[training,], importance=TRUE,
                     proximity=TRUE,strata=Specie)
print(rf.iris)
```



### OLIVE DATA

```{r olive,cache=TRUE,echo=FALSE,results='asis',message=FALSE,warning=FALSE}
setwd("/Users/nataliadasilva/Documents/PP.forest/PP.Forest/data")
load("olive.rda")
library(ggplot2)

d.olive2 <- subset(d.olive,Region%in%c(1,2))[,-2]
d.olive2$Region <- factor(d.olive2$Region)

training <- train_fn(d.olive2[,1],.9)

boot<-bootstrap_pp(data=d.olive2,training=training,ntree=50,index="LDA") 
 b.pp <- bagging_pp(d.olive2,scale=TRUE, strata=TRUE,boot,training)

  

result.boot2.st <- mlply(data.frame(nt=c(5,10,50,100,500)), function(nt) {
  bootstrap_pp(data=d.olive2,scale=TRUE,size.p=.9,training=training,strata=TRUE,ntree=nt,index="LDA") 
   }  
)  

 

result.bagg2.st <- llply(result.boot2.st[1:5],function(x) bagging_pp(data=d.olive2,scale=TRUE,strata=TRUE,boot=x,training=training))

error.st <- sapply(result.bagg2.st,function(x) x[[1]][1] )

```


```{r table.olive,echo=FALSE,dependson='olive',results='asis',message=FALSE,warning=FALSE}
library(xtable)
aux <- c(5,10,50,100,500)

aaa<-xtable(cbind(aux,error,error.st),digits=5,caption="OOB error for PP.bagging with bootstrap samples without strata and with strata")
###
print(aaa,caption.placement="top",include.rownames=TRUE,include.colnames=TRUE)

```


```{r pp.olive,dependson='olive',cache=TRUE,echo=FALSE}
library(PPtree)
Tree.result <-  LDA.Tree(d.olive2[training,1],d.olive2[training,2:9])



test <- d.olive2[-training,]
res<-PP.classify(d.olive2[training,2:9],d.olive2[training,1],Tree.result,1)

print(res[[1]]/length(res[[2]]))

```

Using random forest the OOb error us 0\%

```{r rf.olive,dependson='olive',cache=TRUE,echo=FALSE}
library(randomForest)

rf <- randomForest(Region ~ ., data=d.olive2[training,], importance=TRUE,strata=Region,
             proximity=TRUE)

print(rf )

```


Basic Output of PPforest for ntree=50

```{r olive2,depenson='olive',cache=TRUE,echo=FALSE}

boot<-bootstrap_pp(data=d.olive2,training=training,ntree=50,index="LDA") 
 b.pp <- bagging_pp(d.olive2,scale=TRUE, strata=TRUE,boot,training)

 print(b.pp)

```

Corss validation



```{r data.cv,cache=TRUE,echo=FALSE}
setwd("./data")
crab.aux <- read.csv("australian-crabs.csv",header=T)[,-3]
crab <-data.frame(Type=with(crab.aux,paste(species,sex,sep="")),crab.aux[,-c(1,2)])
leukemia <- read.csv( "Leuk-tot.csv",header=T)
lymphoma <- read.csv("Lymp-tot.csv",header=T)
NCI60 <- read.csv("NCI60.csv",header=T)
wine <- read.csv( "wine.csv", header=T)
glass <- read.csv("glass.csv",header=T)
fishcatch <- read.csv("fishcatch.csv",header=T)[,-1]
names(fishcatch)[1]<- "Type"
image <- read.csv("image.csv",header=T  )
parkinson <- read.csv("parkinsons.csv",header=T)

#temp = list.files(pattern="*.csv")
#myfiles = lapply(temp, read.delim)
```


 



```{r}
library(PPtree)
library(rpart)
library(randomForest)


```
```{r cv,dependson="data.cv",cache=TRUE,echo=FALSE}


#PPtree
lda.err <- function(tr,te){
ppt.lda <-LDA.Tree(tr[,1],tr[,-1])

ppt.pred.tr <-PP.classify(tr[,-1], tr[,1],ppt.lda , Rule=1)

ppt.pred.te <-PP.classify(te[,-1], te[,1],ppt.lda , Rule=1)

 err.tr <- ppt.pred.tr[[1]]/length(ppt.pred.tr[[2]])

 err.te <- ppt.pred.te[[1]]/length(ppt.pred.te[[2]])
data.frame(err.tr,err.te)

}


#CART
cart.err <- function(tr,te){
 cart<- rpart(as.factor(Type)~.,data=tr)
  fit.preds.tr <- predict(cart,newdata=tr,type="class")
 fit.preds.te <- predict(cart,newdata=te,type="class")
fit.table.tr <- table(tr[,1],fit.preds.tr)
fit.table.te <- table(te[,1],fit.preds.te)
err.tr <- (dim(tr)[1]-sum(diag(fit.table.tr)))/dim(tr)[1]
err.te <- (dim(te)[1]-sum(diag(fit.table.te)))/dim(te)[1]
data.frame(err.tr,err.te)
}

#RF
rf.err <- function(tr,te){
rf <- randomForest(as.factor(Type) ~ ., data=tr)
 err.tr <- (dim(tr)[1]-sum(diag(rf$confusion[,-dim(rf$confusion)[2]])))/dim(tr)[1]
 fit.preds.te <- predict(rf,newdata=te,type="class")
fit.table.te <- table(te[,1],fit.preds.te)
err.te <- (dim(te)[1]-sum(diag(fit.table.te)))/dim(te)[1]
data.frame(err.tr,err.te)
}

#PP.RF

pprf.err <- function(data,tr,te,tr.index,te.index){
bo.pp <- bootstrap_pp(data=data,scale=TRUE,size.p=.9,training=tr.index,strata=FALSE,ntree=5,index="LDA")      
ba.pp <- bagging_pp(data,scale=TRUE, strata=FALSE,bo.pp,tr.index,te.index)
data.frame(ba.pp[[2]],ba.pp[[3]])
}


cv.meth <- function(data) {

rdply(10 , function(){
  tr.index <- train_fn(data[,1],2/3)
  te.index <- as.vector(1:length(data[,1]))[!(1:length(data[,1])%in%(tr.index))]
 training<- data[tr.index,]
test <- data[-tr.index,] 
data.frame(lda=lda.err(training,test),cart=cart.err(training,test),rf=rf.err(training,test),pprf=pprf.err(data,training,test,tr.index,te.index)) 
})
}

```

```{r}


load("/Users/nataliadasilva/Box Sync/PP.forest/PP.Forest/data/CVwine2.Rdata")

wine.lda<- data.frame(results=round(apply(wine.errors2,2,mean),5))

load("/Users/nataliadasilva/Box Sync/PP.forest/PP.Forest/data/CVlymphoma.Rdata")
lymphomacv.lda<- data.frame(results=round(apply(lymphoma.errors2,2,mean),5))


aux<-data.frame(rownames(wine.lda)[-1],wine.lda[-1,],lymphomacv.lda[-1,])
res<-data.frame(t(aux[c(1,3,5,7),2:3]),t(aux[c(2,4,6,8),2:3]))
colnames(res)<-c("lda.tr","cart.tr","rf.tr","pp.rf.tr","lda.te","cart.te","rf.te","pp.rf.te")
rownames(res)<-c("Wind.lda","lymphoma.lda")
res
```

